apiVersion: v1
kind: Service
metadata:
  name: report
spec:
  ports:
  - name: report
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: list
    port: 90
    protocol: TCP
    targetPort: 8090
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app: nginx
    app.kubernetes.io/managed-by: starboard
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app: nginx
      app.kubernetes.io/managed-by: starboard
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/managed-by: starboard
        app: nginx
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: storage
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-conf
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.16.1-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx/html/reports/
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      - command:
        - /manager
        args:
        - --leader-elect
        - --namespace=$(NAMESPACE_WATCH)
        image: quay.io/pengli1707/starboardcontroller:v0.0.4
        env:
        - name: NAMESPACE_WATCH
          valueFrom:
            configMapKeyRef:
              name: report
              key: namespaceWatch
        volumeMounts:
        - name: storage
          mountPath: /report
        name: manager
        ports:
        - containerPort: 8090
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 300Mi
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
