# permissions for end users to edit configauditreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configauditreport-editor-role
rules:
- apiGroups:
  - aquasecurity.github.io.my.domain
  resources:
  - configauditreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aquasecurity.github.io.my.domain
  resources:
  - configauditreports/status
  verbs:
  - get
