# permissions for end users to view configauditreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configauditreport-viewer-role
rules:
- apiGroups:
  - aquasecurity.github.io.my.domain
  resources:
  - configauditreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aquasecurity.github.io.my.domain
  resources:
  - configauditreports/status
  verbs:
  - get
