# permissions for end users to view configauditreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aquasecurity.github.io
  resources:
  - configauditreports
  - vulnerabilityreports
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - aquasecurity.github.io
  resources:
  - configauditreports/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - delete
  - list
  - watch